volumes:
  pg_data:
  static:

services:
  db_new:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postrgersql/data
  backend:
    build: ./backend/
    env_file: .env
    depends_on:
      - db_new
    volumes:
      - static:/backend_static
  frontend:
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    build: ./gateway/
    ports:
      - 8000:80
    volumes:
      - static:/staticfiles
    depends_on:
      - backend
